/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109468-gd39b34123d-20221229"
#endif /* AVUTIL_FFVERSION_H */
